shell = "zsh"


[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"


[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.powerlevel10k-config]
local = "~/.config/zsh/p10k-config"
use = [".p10k.zsh"]

[plugins.F-Sy-H]
github = "z-shell/F-Sy-H"
apply = ["defer"]

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
use = ["zeno.zsh"]
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]
