shell = "zsh"

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.powerlevel10k-config]
local = "~/.config/zsh/p10k-config"
use = [".p10k.zsh"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
apply = ["defer"]

[plugins.zeno.hooks]
pre = "source ~/.config/zsh/zeno/zeno_env.zsh"
post = "zsh-defer source ~/.config/zsh/zeno/zeno_bindkey.zsh" # 読み込まれない側をdeferしちゃえばいいらしい
